name = "DeviantsCraft"
author = "Dementore711"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d23b07a5fe07c2892d4c9856e87854fd4615f187a43687ce90a5cfe7448f302"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
