name = "DeviantsCraft"
author = "Dementore711"
version = "1.3.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e38123de5de508b10ad41170b818bfdc6f10947dab914fe2e5c2c31f322c084c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
