name = "DeviantsCraft"
author = "Dementore711"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dae2263a1af478e28b0beac15c95eebfffacc992ef6015a528c2a0a8d4ff583"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
