name = "DeviantsCraft"
author = "Dementore711"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83a4536d4e19b38e97cea0ab4128c1e5e0a56041166fe0f875e6e4568bed4c3f"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
