name = "DeviantsCraft"
author = "Dementore711"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2fd8620703fec4a329c74641c934d6dce961eb7140dda5de377f5e49ef32c04"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
