name = "DeviantsCraft"
author = "Dementore711"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "309647f1043c792bc95b38bfc3d392be5aaf46e0b23fceec4571eb9196d9724a"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
