name = "DeviantsCraft"
author = "Dementore711"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e8665471367d777b86ee60fa1f0883715c01675db966455bf9887a9bc7d058c"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
