name = "DeviantsCraft"
author = "Dementore711"
version = "1.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60a7f4df21cceeaa6324421c4f07f973c772b82ba3c96e24359ea5a4f752623b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
