name = "DeviantsCraft"
author = "Dementore711"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fb9067d9438506368fd8165f00b34d5b92f843699fdeff523113a9b1b356272"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
