name = "DeviantsCraft"
author = "Dementore711"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2ede16832820399b833dc38f2bae5c58c22922fd2967362be46395e2e458cb5"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
