name = "DeviantsCraft"
author = "Dementore711"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96332abdd6d2c8d75ca995c39c0400b82ac7668290e8751ac196fc07dff0c196"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
